using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using TedToolkit.RoslynHelper;
using Accessibility = Microsoft.CodeAnalysis.Accessibility;

namespace TedToolkit.Orchestration.Pipeline.Analyzer;

internal static class StepContextEmitter
{
    private const string ContextHintSuffix = ".StepContext.g.cs";

    internal const string CompositeAttributeName =
        "TedToolkit.Orchestration.Pipeline.Attributes.CompositeStepAttribute";
    internal const string LoggerAttributeName =
        "TedToolkit.Orchestration.Pipeline.Attributes.StepLoggerAttribute";

    internal static StepContextSource? TryCreate(
        GeneratorSyntaxContext context, CancellationToken cancellationToken)
    {
        var declaration = (StructDeclarationSyntax)context.Node;
        var type = context.SemanticModel.GetDeclaredSymbol(
            declaration, cancellationToken) as INamedTypeSymbol;
        if (type is null || !CanGenerate(type, context.SemanticModel.Compilation))
            return null;
        var first = type.DeclaringSyntaxReferences.FirstOrDefault();
        if (first is null || first.SyntaxTree != declaration.SyntaxTree || first.Span != declaration.Span)
            return null;
        return new StepContextSource(
            GeneratedNames.MetadataName(type),
            GeneratedNames.HintName(type, ContextHintSuffix),
            Source(type));
    }

    internal static ImmutableArray<GeneratedSource> Resolve(
        ImmutableArray<StepContextSource> sources)
    {
        var collisions = new HashSet<string>(sources
            .GroupBy(source => source.HintName, StringComparer.Ordinal)
            .Where(group => group.Count() > 1)
            .Select(group => group.Key), StringComparer.Ordinal);
        var result = ImmutableArray.CreateBuilder<GeneratedSource>(sources.Length);
        foreach (var source in sources)
        {
            var hintName = collisions.Contains(source.HintName)
                ? GeneratedNames.DisambiguateHintName(
                    source.HintName, source.MetadataName, ContextHintSuffix)
                : source.HintName;
            result.Add(new GeneratedSource(hintName, source.Source));
        }
        return result.MoveToImmutable();
    }

    internal static bool HasAttribute(INamedTypeSymbol type, string metadataName) =>
        type.GetAttributes().Any(attribute => attribute.AttributeClass?.ToDisplayString() == metadataName);

    internal static bool CanGenerate(INamedTypeSymbol type, Compilation compilation)
    {
        if (type.TypeKind != TypeKind.Struct || !type.IsRefLikeType || !type.IsReadOnly ||
            type.Arity != 0 || type.ContainingType is not null || type.IsFileLocal ||
            HasExplicitLayout(type) || !type.DeclaringSyntaxReferences.Any(reference =>
                reference.GetSyntax() is Microsoft.CodeAnalysis.CSharp.Syntax.StructDeclarationSyntax declaration &&
                declaration.Modifiers.Any(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PartialKeyword)))
            return false;
        if (StepSymbols.IsLeafStep(type, compilation))
            return StepSymbols.InvalidContract(type, compilation) is null;
        return HasAttribute(type, CompositeAttributeName) &&
            CompositeStepGenerator.ContractError(type, compilation) is null;
    }

    internal static bool HasExplicitLayout(INamedTypeSymbol type) => type.GetAttributes().Any(attribute =>
        attribute.AttributeClass?.ToDisplayString() == "System.Runtime.InteropServices.StructLayoutAttribute" &&
        attribute.ConstructorArguments.FirstOrDefault().Value is int value &&
        value == (int)System.Runtime.InteropServices.LayoutKind.Explicit);

    private static string Source(INamedTypeSymbol type)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        if (!type.ContainingNamespace.IsGlobalNamespace)
        {
            builder.Append("namespace ").Append(GeneratedNames.Namespace(type.ContainingNamespace)).AppendLine(";");
            builder.AppendLine();
        }
        builder.Append(type.DeclaredAccessibility == Accessibility.Public ? "public " : "internal ")
            .Append("readonly ref partial struct ").Append(type.Name.ToValidIdentifier()).AppendLine();
        builder.AppendLine("{");
        builder.AppendLine("    /// <summary>Gets the configured identity of this Step instance.</summary>");
        builder.AppendLine("    public required string DisplayName { get; init; }");
        if (HasAttribute(type, LoggerAttributeName))
        {
            builder.AppendLine("    /// <summary>Gets the logger created for this Step instance.</summary>");
            builder.AppendLine("    public required global::Microsoft.Extensions.Logging.ILogger Logger { get; init; }");
        }
        builder.AppendLine("}");
        return builder.ToString();
    }
}

internal sealed class StepContextSource : IEquatable<StepContextSource>
{
    internal StepContextSource(string metadataName, string hintName, string source)
    {
        MetadataName = metadataName;
        HintName = hintName;
        Source = source;
    }

    internal string MetadataName { get; }
    internal string HintName { get; }
    internal string Source { get; }

    public bool Equals(StepContextSource? other) => other is not null &&
        StringComparer.Ordinal.Equals(MetadataName, other.MetadataName) &&
        StringComparer.Ordinal.Equals(HintName, other.HintName) &&
        StringComparer.Ordinal.Equals(Source, other.Source);

    public override bool Equals(object? obj) => Equals(obj as StepContextSource);

    public override int GetHashCode()
    {
        unchecked
        {
            var hash = StringComparer.Ordinal.GetHashCode(MetadataName);
            hash = (hash * 397) ^ StringComparer.Ordinal.GetHashCode(HintName);
            return (hash * 397) ^ StringComparer.Ordinal.GetHashCode(Source);
        }
    }
}
