using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace TedToolkit.Orchestration.StateMachine.Analyzer;

public sealed partial class StateMachineGenerator
{
    private static string Emit(MachineModel model)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        var namespaceName = model.Machine.ContainingNamespace.IsGlobalNamespace
            ? null
            : model.Machine.ContainingNamespace.ToDisplayString();
        if (namespaceName is not null)
        {
            builder.Append("namespace ").Append(namespaceName).AppendLine(";");
            builder.AppendLine();
        }
        builder.Append(model.Machine.DeclaredAccessibility == Accessibility.Public ? "public " : "internal ")
            .Append("sealed partial class ").Append(Identifier(model.Machine.Name)).Append(" : ")
            .Append("global::TedToolkit.Orchestration.StateMachine.StateMachine<")
            .Append(model.StateType.ToDisplayString(TypeFormat)).AppendLine(">");
        builder.AppendLine("{");
        builder.Append("    public ").Append(Identifier(model.Machine.Name)).Append('(')
            .Append(model.StateType.ToDisplayString(TypeFormat)).AppendLine(" initialState) : base(initialState)");
        builder.AppendLine("    {");
        builder.AppendLine("    }");
        if (model.InitialState is not null)
        {
            builder.AppendLine();
            builder.Append("    public ").Append(Identifier(model.Machine.Name)).Append("() : this(")
                .Append(model.InitialState).AppendLine(")");
            builder.AppendLine("    {");
            builder.AppendLine("    }");
        }
        foreach (var trigger in model.Triggers)
        {
            builder.AppendLine();
            EmitTrigger(builder, model, trigger);
        }
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void EmitTrigger(StringBuilder builder, MachineModel model, TriggerModel trigger)
    {
        var parameters = Parameters(trigger.Method, includeCancellationDefault: false);
        var companionParameters = Parameters(trigger.Method, includeCancellationDefault: true);
        var arguments = string.Join(", ", trigger.Method.Parameters.Select(parameter => Identifier(parameter.Name)));
        var stateType = model.StateType.ToDisplayString(TypeFormat);

        builder.Append("    public partial async global::System.Threading.Tasks.ValueTask ")
            .Append(Identifier(trigger.Method.Name)).Append('(').Append(parameters).AppendLine(")");
        builder.AppendLine("    {");
        builder.Append("        var __result = await ").Append(Identifier(trigger.TryName)).Append('(').Append(arguments)
            .AppendLine(").ConfigureAwait(false);");
        builder.AppendLine("        if (!__result.Succeeded)");
        builder.Append("            throw new global::TedToolkit.Orchestration.StateMachine.TriggerRejectedException(nameof(")
            .Append(Identifier(trigger.Method.Name)).AppendLine("), __result.Source, __result.Rejection!.Value);");
        builder.AppendLine("    }");

        builder.AppendLine();
        builder.Append("    public async global::System.Threading.Tasks.ValueTask<global::TedToolkit.Orchestration.StateMachine.TriggerResult<")
            .Append(stateType).Append(">> ").Append(Identifier(trigger.TryName)).Append('(').Append(companionParameters).AppendLine(")");
        builder.AppendLine("    {");
        builder.AppendLine("        if (IsConsumerCallbackActive)");
        builder.Append("            throw new global::TedToolkit.Orchestration.StateMachine.ReentrantTriggerException(nameof(")
            .Append(Identifier(trigger.Method.Name)).AppendLine("), State);");
        builder.AppendLine("        var __source = State;");
        builder.AppendLine("        switch (__source)");
        builder.AppendLine("        {");
        foreach (var group in trigger.Routes.GroupBy(route => route.Source, StringComparer.Ordinal))
            EmitTryGroup(builder, stateType, trigger, group.ToArray());
        builder.AppendLine("            default:");
        builder.Append("                return global::TedToolkit.Orchestration.StateMachine.TriggerResult<").Append(stateType)
            .AppendLine(">.Rejected(__source, global::TedToolkit.Orchestration.StateMachine.TriggerRejection.NotPermitted);");
        builder.AppendLine("        }");
        builder.AppendLine("    }");

        builder.AppendLine();
        builder.Append("    public async global::System.Threading.Tasks.ValueTask<bool> ").Append(Identifier(trigger.CanName))
            .Append('(').Append(companionParameters).AppendLine(")");
        builder.AppendLine("    {");
        builder.AppendLine("        var __source = State;");
        builder.AppendLine("        switch (__source)");
        builder.AppendLine("        {");
        foreach (var group in trigger.Routes.GroupBy(route => route.Source, StringComparer.Ordinal))
            EmitCanGroup(builder, trigger, group.ToArray());
        builder.AppendLine("            default:");
        builder.AppendLine("                return false;");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
    }

    private static void EmitTryGroup(StringBuilder builder, string stateType, TriggerModel trigger, RouteModel[] routes)
    {
        builder.Append("            case ").Append(routes[0].Source).AppendLine(":");
        builder.AppendLine("            {");
        var candidates = routes.Where(route => !route.IsFallback).ToArray();
        var fallback = routes.SingleOrDefault(route => route.IsFallback);
        if (candidates.Length == 1 && candidates[0].Guard is null)
        {
            EmitTransition(builder, stateType, candidates[0], 16);
            builder.AppendLine("            }");
            return;
        }
        builder.AppendLine("                var __matches = 0;");
        builder.AppendLine("                var __target = __source;");
        builder.AppendLine("                var __accepted = false;");
        foreach (var candidate in candidates)
        {
            EmitGuardEvaluation(builder, candidate.Guard!, "__accepted", 16);
            builder.AppendLine("                if (__accepted)");
            builder.AppendLine("                {");
            builder.AppendLine("                    __matches++;");
            builder.Append("                    __target = ").Append(candidate.Target).AppendLine(";");
            builder.AppendLine("                }");
        }
        builder.AppendLine("                if (__matches > 1)");
        builder.Append("                    throw new global::TedToolkit.Orchestration.StateMachine.AmbiguousTransitionException(nameof(")
            .Append(Identifier(trigger.Method.Name)).AppendLine("), __source);");
        builder.AppendLine("                if (__matches == 1)");
        builder.AppendLine("                {");
        EmitSelectedTransition(builder, stateType, candidates, 20);
        builder.AppendLine("                }");
        if (fallback is not null) EmitTransition(builder, stateType, fallback, 16);
        else
            builder.Append("                return global::TedToolkit.Orchestration.StateMachine.TriggerResult<").Append(stateType)
                .AppendLine(">.Rejected(__source, global::TedToolkit.Orchestration.StateMachine.TriggerRejection.GuardRejected);");
        builder.AppendLine("            }");
    }

    private static void EmitTransition(StringBuilder builder, string stateType, RouteModel route, int spaces)
    {
        var indent = new string(' ', spaces);
        EmitActionCall(builder, route.ExitAction, spaces);
        builder.Append(indent).Append("State = ").Append(route.Target).AppendLine(";");
        builder.Append(indent).Append("RaiseTransitioned(__source, ").Append(route.Target).AppendLine(");");
        EmitActionCall(builder, route.EntryAction, spaces);
        EmitActionCall(builder, route.EntryFromAction, spaces);
        builder.Append(indent).Append("RaiseTransitionCompleted(__source, ").Append(route.Target).AppendLine(");");
        builder.Append(indent).Append("return global::TedToolkit.Orchestration.StateMachine.TriggerResult<").Append(stateType)
            .Append(">.Success(__source, ").Append(route.Target).AppendLine(");");
    }

    private static void EmitSelectedTransition(StringBuilder builder, string stateType,
        IReadOnlyList<RouteModel> routes, int spaces)
    {
        var indent = new string(' ', spaces);
        EmitActionCall(builder, routes[0].ExitAction, spaces);
        builder.Append(indent).AppendLine("State = __target;");
        builder.Append(indent).AppendLine("RaiseTransitioned(__source, __target);");
        var entries = routes.GroupBy(route => route.Target, StringComparer.Ordinal)
            .Select(group => group.First())
            .Where(route => route.EntryAction is not null || route.EntryFromAction is not null).ToArray();
        if (entries.Length != 0)
        {
            builder.Append(indent).AppendLine("switch (__target)");
            builder.Append(indent).AppendLine("{");
            foreach (var route in entries)
            {
                builder.Append(indent).Append("    case ").Append(route.Target).AppendLine(":");
                EmitActionCall(builder, route.EntryAction, spaces + 8);
                EmitActionCall(builder, route.EntryFromAction, spaces + 8);
                builder.Append(indent).AppendLine("        break;");
            }
            builder.Append(indent).AppendLine("}");
        }
        builder.Append(indent).AppendLine("RaiseTransitionCompleted(__source, __target);");
        builder.Append(indent).Append("return global::TedToolkit.Orchestration.StateMachine.TriggerResult<").Append(stateType)
            .AppendLine(">.Success(__source, __target);");
    }

    private static void EmitActionCall(StringBuilder builder, ActionModel? action, int spaces)
    {
        if (action is null) return;
        var indent = new string(' ', spaces);
        var call = Identifier(action.Method.Name) + "(" + string.Join(", ", action.Arguments) + ")";
        builder.Append(indent).AppendLine("using (EnterConsumerCallback())");
        builder.Append(indent).AppendLine("{");
        builder.Append(indent).Append("    ");
        if (action.IsAsync) builder.Append("await ");
        builder.Append(call);
        if (action.IsAsync) builder.Append(".ConfigureAwait(false)");
        builder.AppendLine(";");
        builder.Append(indent).AppendLine("}");
    }

    private static void EmitCanGroup(StringBuilder builder, TriggerModel trigger, RouteModel[] routes)
    {
        builder.Append("            case ").Append(routes[0].Source).AppendLine(":");
        builder.AppendLine("            {");
        var candidates = routes.Where(route => !route.IsFallback).ToArray();
        var fallback = routes.SingleOrDefault(route => route.IsFallback);
        if (candidates.Length == 1 && candidates[0].Guard is null)
        {
            builder.AppendLine("                return true;");
            builder.AppendLine("            }");
            return;
        }
        builder.AppendLine("                var __matches = 0;");
        builder.AppendLine("                var __accepted = false;");
        foreach (var candidate in candidates)
        {
            EmitGuardEvaluation(builder, candidate.Guard!, "__accepted", 16);
            builder.AppendLine("                if (__accepted) __matches++;");
        }
        builder.AppendLine("                if (__matches > 1)");
        builder.Append("                    throw new global::TedToolkit.Orchestration.StateMachine.AmbiguousTransitionException(nameof(")
            .Append(Identifier(trigger.Method.Name)).AppendLine("), __source);");
        builder.Append("                return __matches == 1").Append(fallback is null ? ";" : " || __matches == 0;").AppendLine();
        builder.AppendLine("            }");
    }

    private static string GuardCall(GuardModel guard)
    {
        var call = Identifier(guard.Method.Name) + "(" + string.Join(", ", guard.Arguments) + ")";
        return guard.IsAsync ? "await " + call + ".ConfigureAwait(false)" : call;
    }

    private static void EmitGuardEvaluation(StringBuilder builder, GuardModel guard, string result, int spaces)
    {
        var indent = new string(' ', spaces);
        builder.Append(indent).AppendLine("using (EnterConsumerCallback())");
        builder.Append(indent).AppendLine("{");
        builder.Append(indent).Append("    ").Append(result).Append(" = ").Append(GuardCall(guard)).AppendLine(";");
        builder.Append(indent).AppendLine("}");
    }

    private static string Parameters(IMethodSymbol method, bool includeCancellationDefault)
    {
        return string.Join(", ", method.Parameters.Select(parameter =>
        {
            var modifier = parameter.IsParams ? "params " : "";
            var result = modifier + parameter.Type.ToDisplayString(TypeFormat) + " " + Identifier(parameter.Name);
            if (includeCancellationDefault && IsCancellationToken(parameter.Type) && parameter.HasExplicitDefaultValue)
                result += " = default";
            return result;
        }));
    }
    private static string Identifier(string value) =>
        SyntaxFacts.GetKeywordKind(value) != SyntaxKind.None ? "@" + value : value;

    private static string HintName(INamedTypeSymbol machine)
    {
        var name = machine.ToDisplayString().Replace('<', '_').Replace('>', '_').Replace('.', '_').Replace('+', '_');
        return name + ".StateMachine.g.cs";
    }
}